package com.kirayeazerbaijan.kirayeaz.Profile.TabViewPager.NewAds

class CityAzerbaijan {
    fun city(): Array<String> {
        return arrayOf(
            "Агдам - Ağdam",
            "Агдаш - Ağdaş",
            "Агдере - Ağdərə",
            "Агджабеди - Ağcabədi",
            "Агстафа - Ağstafa",
            "Аджикабул - Hacıqabul",
            "Астара - Astara",
            "Ахсу - Ağsu",
            "Бабек - Babək",
            "Баку - Bakı",
            "Балакен - Balakən",
            "Барда - Bərdə",
            "Бейлаган - Beyləqan",
            "Билясувар - Biləsuvar",
            "Габала - Qəbələ",
            "Газах - Qazax",
            "Гах - Qax",
            "Геранбой - Goranboy",
            "Гёйгёль - Göygöl",
            "Гёйтепе - Göytəpə",
            "Гёйчай - Göyçay",
            "Гобустан - Qobustan",
            "Говлар - Qovlar",
            "Горадиз - Horadiz",
            "Губа - Quba",
            "Губадлы - Qubadlı",
            "Гусар - Qusar",
            "Гянджа - Gəncə",
            "Далимамедли - Dəliməmmədli",
            "Дашкесан - Daşkəsən",
            "Джалилабад - Cəlilabad",
            "Джебраил - Cəbrayıl",
            "Джульфа - Culfa",
            "Евлах - Yevlax",
            "Загатала - Zaqatala",
            "Зангелан - Zəngilan",
            "Зердаб - Zərdab",
            "Имишли - İmişli",
            "Исмаиллы - İsmayıllı",
            "Кедабек - Gədəbəy",
            "Кельбаджар - Kəlbəcər",
            "Кюрдамир - Kürdəmir",
            "Лачын - Laçın",
            "Ленкорань - Lənkəran",
            "Лерик - Lerik",
            "Лиман - Liman",
            "Масаллы - Masallı",
            "Мингечевир - Mingəçevir",
            "Нафталан - Naftalan",
            "Нахчыван - Naxçıvan",
            "Нефтечала - Neftçala",
            "Огуз - Oğuz",
            "Ордубад - Ordubad",
            "Саатлы - Saatlı",
            "Сабирабад - Sabirabad",
            "Сальян - Salyan",
            "Самух - Samux",
            "Сиазань - Siyəzən",
            "Сумгайыт - Sumqayıt",
            "Тертер - Tərtər",
            "Товуз - Tovuz",
            "Уджар - Ucar",
            "Физули - Füzuli",
            "Ханкенди - Xankəndi",
            "Хачмаз - Xaçmaz",
            "Ходжавенд - Xocavənd",
            "Ходжалы - Xocalı",
            "Худат - Xudat",
            "Хызы - Xızı",
            "Хырдалан - Xırdalan",
            "Шабран - Şabran",
            "Шамкир - Şəmkir",
            "Шарур - Şərur",
            "Шахбуз - Şahbuz",
            "Шеки - Şəki",
            "Шемахы - Şamaxı",
            "Ширван - Şirvan",
            "Шуша - Şuşa",
            "Ярдымлы"
        )
    }

}